Enables top level menu plus submenus
eighteen73/settings-api pull request #3
Opened 2022-12-12 22:48 UTC by alexmigf

Adds a new `$top_level` argument to the construct to enable top level menus, it's disabled by default using the **Settings** menu.

Using the `set_submenu` method is possible to add submenu pages to top level menus, eg.

```php
use Eighteen73\SettingsApi\SettingsApi;

$settings = new SettingsApi(
	'Plugin Settings',
	'Plugin Settings',
	'manage_options',
	'plugin-name',
	3,
	true
);

$settings->set_submenu(
	'Submenu 1',
	'Submenu 1',
	'plugin-name-submenu',
	array( $this, 'callback_function' ),
);
```

2022-12-13 08:33 UTC, brettsmason requested changes

2022-12-13 08:33 UTC, brettsmason commented on includes/classes/SettingsApi.php
> +		$this->submenus_array[] = array(
Could this be changed to use the short array syntax please?

2022-12-13 08:33 UTC, brettsmason commented on includes/classes/SettingsApi.php
> +	public function __construct( $page_title, $menu_title, $capability, $slug, $position = null, $top_level = false ) {
Looks like a new `$icon_url` parameter was added but needs adding to the constructor too

2022-12-13 08:34 UTC, brettsmason commented
Thanks for another PR! I left a few comments for a couple of things I noticed.
If possible would you mind documenting these changes in the readme too? No worries if not, I can document the changes after its merged if needed.

2022-12-15 18:53 UTC, alexmigf commented
@brettsmason done.

2022-12-15 19:57 UTC, brettsmason commented
Thanks, will take a look tomorrow

2022-12-22 08:11 UTC, brettsmason commented
@alexmigf Apologies for the delay. We may well look at refactoring how menus are created in the future, but for now this looks good 👍

2022-12-22 08:11 UTC, merged